services:
  db:
    image: postgres
    user: postgres
    env_file: .env
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5
  server:
    image: typed-app
    env_file: .env
    environment:
      DB_HOST: db
    build:
      context: .
    ports:
      - 3000:3000
    depends_on:
      db:
        condition: service_healthy
volumes:
  db-data:
